{% set name = "typstfmt" %}
{% set version = "0.2.10" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/astrale-sharp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5a3f413a428b2590552c2d0ab0ab04c7a745e1cca128844b7b82ea49326d65c4

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstfmt --version

about:
  home: https://github.com/astrale-sharp/typstfmt
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY_LICENSES.yaml
  summary: A formatter for typst.

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
