{% set name = "typstfmt" %}
{% set version = "0.2.7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/astrale-sharp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 17db7ddb83a8e2e43b3b34f19dcc8cbd3585aea34e05a5689e6f5beda27ac523

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstfmt --version

about:
  home: https://github.com/astrale-sharp/typstfmt
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY_LICENSES.yaml
  summary: A formatter for typst.

extra:
  recipe-maintainers:
    - pavelzw
