{% set name = "typstfmt" %}
{% set version = "0.2.8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/astrale-sharp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c884ea06a8f1d04fa12ea582f11b3520e09c337fb42855b3b49175f1e4b8a57

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstfmt --version

about:
  home: https://github.com/astrale-sharp/typstfmt
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY_LICENSES.yaml
  summary: A formatter for typst.

extra:
  recipe-maintainers:
    - pavelzw
