{% set name = "typstfmt" %}
{% set version = "0.2.9" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/astrale-sharp/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: fa24ee1705ff5fec4db45e301d38439d0bd3d6d4ee04b280ba997b2f94ba16d9

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstfmt --version

about:
  home: https://github.com/astrale-sharp/typstfmt
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY_LICENSES.yaml
  summary: A formatter for typst.

extra:
  recipe-maintainers:
    - pavelzw
